name: Build & Test

on:
  pull_request:
    branches:
      - main

env:
  GO_VERSION: "1.24"

jobs:
  build_and_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}

      - name: Download dependencies
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m

      - name: Run tests
        run: go test -v

      - name: Build
        run: |
          go install xcaddy
          xcaddy build \
              --with github.com/mholt/caddy-dynamicdns \
              --with github.com/mietzen/caddy-dynamicdns-cmd-source=.
